# Generated by Django 3.2.1 on 2021-05-04 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='relations',
            field=models.ManyToManyField(blank=True, related_name='parent', to='issue.Issue'),
        ),
    ]
