# Generated by Django 3.2.1 on 2021-05-06 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0007_alter_issue_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files/')),
            ],
        ),
        migrations.AddField(
            model_name='issue',
            name='files',
            field=models.ManyToManyField(blank=True, related_name='issue', to='issue.File'),
        ),
    ]
